services:
#    forms.example:
#        class: FormsBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
#    forms.form.personage:
#        class: FormsBundle\Form\PersonageType
#        arguments: ["@forms.my_service"]
#        tags:
#            - { name: form.type }